let day;
switch (new Date().getDate()) {
  case 1:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Relativpronomen</span></h2><div class="grid-container55"><div><span style="color:red;">Kasus</span></div><div>M.</div><div>F.</div><div>N.</div><div>Pl.</div><div><span style="color:black;">Nominativ</span></div><div><span style="color:blue;">der</span></div><div><span style="color:red;">die</span></div><div><span style="color:green;">das</span></div><div><span style="color:orange;">die</span></div><div><span style="color:black;">Akkusativ</span></div><div><span style="color:blue;">den</span></div><div><span style="color:red;">die</span></div><div><span style="color:green;">das</span></div><div><span style="color:orange;">die</span></div><div><span style="color:black;">Dativ</span></div><div><span style="color:blue;">dem</span></div><div><span style="color:red;">der</span></div><div><span style="color:green;">dem</span></div><div><span style="color:orange;">denen</span></div><div><span style="color:black;">Genitiv</span></div><div><span style="color:blue;">dessen</span></div><div><span style="color:red;">deren</span></div><div><span style="color:green;">dessen</span></div><div><span style="color:orange;">deren</span></div></div>';
    break;
  case 2:
    day = '<h3>Unbestimmter Artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b>Kasus</b></td><td style="color:blue;"><b>M.</b></td><td style="color:red;"><b>F.</b></td><td style="color:green;"><b>N.</b></td><td><b>Pl.</b></td></tr><tr class="tr2"><td style="color:green;"><b>Nom.</b></td><td style="color:blue;">ein <span style="color:black;">Mann</span></td><td style="color:red;">eine <span style="color:black;">Frau</span></td><td style="color:green;">ein <span style="color:black;">Kind</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr><tr><td style="color:orange;"><b>Gen.</b></td><td style="color:blue;">eines <span style="color:black;">Mann</span><span style="color:orange;">es</span></td><td style="color:red;">einer <span style="color:black;">Frau</span></td><td style="color:green;">eines <span style="color:black;">Kind</span><span style="color:orange;">es</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr><tr class="tr2"><td style="color:red;"><b>Dat.</b></td><td style="color:blue;">einem <span style="color:black;">Mann</span></td><td style="color:red;">einer <span style="color:black;">Frau</span></td><td style="color:green;">einem <span style="color:black;">Kind</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr><tr><td style="color:darkviolet;"><b>Akk.</b></td><td style="color:blue;">einen <span style="color:black;">Mann</span></td><td style="color:red;">eine <span style="color:black;">Frau</span></td><td style="color:green;">ein <span style="color:black;">Kind</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr></tbody></table></div>';
    break;
  case 3:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;">Possessivpronomen Dativ</h2><table><thead><tr class="tr1"><th></th><th class="w3-text-blue"><span style="color:blue;">der</span></th><th><span style="color:green;">das</span></th><th><span style="color:red;">die</span></th><th>Plural</th></tr></thead><tbody><tr><td><b>ich</b></td><td>meinem</td><td>meinem</td><td>meiner</td><td>meinen</td></tr><tr class="tr2"><td><b>du</b></td><td>deinem</td><td>deinem</td><td>deiner</td><td>deinen</td></tr><tr><td><b>er</b></td><td>seinem</td><td>seinem</td><td>seiner</td><td>seinen</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihrem</td><td>ihrem</td><td>ihrer</td><td>ihren</td></tr><tr><td><b>es</b></td><td>seinem</td><td>seinem</td><td>seiner</td><td>seinen</td></tr><tr class="tr2"><td><b>wir</b></td><td>unserem</td><td>unserem</td><td>unserer</td><td>unseren</td></tr><tr><td><b>ihr</b></td><td>euerem</td><td>euerem</td><td>euerer</td><td>eueren</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihrem</td><td>ihrem</td><td>ihrer</td><td>ihren</td></tr><tr><td><b>Sie</b></td><td>Ihrem</td><td>Ihrem</td><td>Ihrer</td><td>Ihren</td></tr></tbody></table></div>';
    break;
  case 4:
    day = '<h3><span style="color:blue;">jeder</span> <span style="color:green;">jedes</span> <span style="color:red;">jede</span></h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td></td><td class="w3-text-blue"><b>M.</b></td><td class="w3-text-green"><b>N.</b></td><td class="w3-text-red"><b>F.</b></td><td><b>Pl.</b></td></tr></thead><tbody class="body1"><tr class="tr2"><td>Nom.</td><td><span style="color:blue;">der</span></td><td><span style="color:green;">das</span></td><td><span style="color:red;">die</span></td><td>die</td></tr><tr><td><b></b></td><td><span style="color:blue;">jeder</span></td><td><span style="color:green;">jedes</span></td><td><span style="color:red;">jede</span></td><td>alle</td></tr><tr class="tr2"><td>Gen.</td><td><span style="color:blue;">des</span></td><td><span style="color:green;">des</span></td><td><span style="color:red;">der</span></td><td>der</td></tr><tr><td><b></b></td><td><span style="color:blue;">jedes</span></td><td><span style="color:green;">jedes</span></td><td><span style="color:red;">jeder</span></td><td>allen</td></tr><tr class="tr2"><td>Dat.</td><td><span style="color:blue;">dem</span></td><td><span style="color:green;">dem</span></td><td><span style="color:red;">der</span></td><td>den</td></tr><tr><td><b></b></td><td><span style="color:blue;">jedem</span></td><td><span style="color:green;">jedem</span></td><td><span style="color:red;">jeder</span></td><td>allen</td></tr><tr class="tr2"><td>Akk.</td><td><span style="color:blue;">den</span></td><td><span style="color:green;">das</span></td><td><span style="color:red;">die</span></td><td>die</td></tr><tr><td><b></b></td><td><span style="color:blue;">jeden</span></td><td><span style="color:green;">jedes</span></td><td><span style="color:red;">jede</span></td><td>alle</td></tr></tbody></table><h6><span style="color:blue;">jeder</span>/<span style="color:green;">jedes</span>/<span style="color:red;">jede</span>: (Singular) bei einer Person/ Ding/ Sache → individuell.</h6><br><h6><span style="color:red;">alle/allen</span>: (Plural) bei vielen Personen/ Dingen/ Sachen → nicht individuell.</h6></div>';
    break;
  case 5:
    day = '<div><h1>Kasus, Numerus, Genus</h1><p><h2><span style="color:red;">Kasus</span></h2><span style="font-size:20px;">&#8594;</span>Fall<br>1.) Nominativ<br>2.) Genitiv<br>3.) Dativ<br>4.) Akkusativ</p><br><p><h2><span style="color:red;">Numerus</span></h2><span style="font-size:20px;">&#8594;</span>Einzahl / Mehrzahl<br>1.) Singular<br>2.) Plural</p><br><p><h2><span style="color:red;">Genus</span></h2><span style="font-size:20px;">&#8594;</span>Geschlecht<br>1.) Maskulin <span style="color:blue;">der</span><br>2.) Feminin <span style="color:red;">die</span><br>3.) Neutral <span style="color:green;">das</span></p></div>';
    break;
  case 6:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;">Possessivpronomen Akkusativ</h2><table><thead><tr class="tr1"><th></th><th><span style="color:blue;">der</span></th><th><span style="color:green;">das</span></th><th><span style="color:red;">die</span></th><th>Plural</th></tr></thead><tbody><tr><td><b>ich</b></td><td>meinen</td><td>mein</td><td>meine</td><td>meine</td></tr><tr class="tr2"><td><b>du</b></td><td>deinen</td><td>dein</td><td>deine</td><td>deine</td></tr><tr><td><b>er</b></td><td>seinen</td><td>sein</td><td>seine</td><td>seine</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihren</td><td>ihr</td><td>ihre</td><td>ihre</td></tr><tr><td><b>es</b></td><td>seinen</td><td>sein</td><td>seine</td><td>seine</td></tr><tr class="tr2"><td><b>wir</b></td><td>unseren</td><td>unser</td><td>unsere</td><td>unsere</td></tr><tr><td><b>ihr</b></td><td>eueren</td><td>euer</td><td>euere</td><td>euere</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihren</td><td>ihr</td><td>ihre</td><td>ihre</td></tr><tr><td><b>Sie</b></td><td>Ihren</td><td>Ihr</td><td>Ihre</td><td>Ihre</td></tr></tbody></table></div>';
    break;
  case 7:
    day = '<div><h1><span style="color:red;">DATIV</span> - Zeitangaben</h1></button> Artikel <span style="color:blue;">der</span> / <span style="color:green;">das</span> im Dativ: =  <span style="color:red;">dem</span><br>Datum/Wochentag:  <span style="color:red;">a</span>n  +  de<span style="color:red;">m</span>  =  <span style="color:red;">am</span>:  <span style="color:red;">am</span> erst<span style="color:red;">en</span>, zweit<span style="color:red;">en</span>, dritt<span style="color:red;">en</span>, viert<span style="color:red;">en</span> .....<br>Monat/Jahreszeit: <span style="color:red;">i</span>n +  de<span style="color:red;">m</span>  =  <span style="color:red;">im</span>:  <span style="color:red;">im</span> Januar, Februar, <span style="color:red;">im</span> Sommer, Herbst .....<br><br><span style="color:red;">FOKUS</span> Verben mit Akkusativ und Dativ<br>Dativ   -   Person <br> Akkusativ   -   Sache </div>';
    break;
  case 8:
    day = '<div class="container mt-" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Pronomen</span></h2><div class="grid-container"><div><span style="color:green;">Nominativ</span></div><div>ich</div><div>du</div><div>er</div><div>sie</div><div>es</div><div>wir</div><div>ihr</div><div>sie</div><div>Sie</div><div><span style="color:darkviolet;">Akkusativ</span></div><div>mich</div><div>dich</div><div>ihn</div><div>sie</div><div>es</div><div>uns</div><div>euch</div><div>sie</div><div>Sie</div><div><span style="color:red;">Dativ</span></div><div>mir</div><div>dir</div><div>ihm</div><div>ihr</div><div>ihm</div><div>uns</div><div>euch</div><div>ihnen</div><div>Ihnen</div><div><span style="color:orange;">Possessiv</span></div><div>mein</div><div>dein</div><div>sein</div><div>ihr</div><div>sein</div><div>unser</div><div>euer</div><div>ihr</div><div>Ihr</div></div></div>';
    break;
  case 9:
    day = '<h3>Negativartikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b></b></td><td><b><span style="color:green;">Nom.</span></b></td><td><b><span style="color:orange;">Genitiv</span></b></td><td><b><span style="color:red;">Dativ</span></b></td><td><b><span style="color:darkviolet;">Akk.</span></b></td></tr></thead><tbody class="body1"><tr class="tr2"><td><b><span style="color:blue;">der</span></b></td><td><span style="color:green;">kein</span> Mann</td><td><span style="color:orange;">keines</span> Mann<span style="color:orange;">es</span></td><td><span style="color:red;">keinem</span> Mann</td><td><span style="color:darkviolet;">keinen</span> Mann</td></tr><tr><td><b><span style="color:red;">die</span></b></td><td><span style="color:green;">keine</span> Frau</td><td><span style="color:orange;">keiner</span> Frau</td><td><span style="color:red;">keiner</span> Frau</td><td><span style="color:darkviolet;">keine</span> Frau</td></tr><tr class="tr2"><td><b><span style="color:green;">das</span></b></td><td><span style="color:green;">kein</span> Kind</td><td><span style="color:orange;">keines</span> Kind<span style="color:orange;">es</span></td><td><span style="color:red;">keinem</span> Kind</td><td><span style="color:darkviolet;">kein</span> Kind</td></tr><tr><td><b>Pl.</b></td><td><span style="color:green;">keine</span> Sterne</td><td><span style="color:orange;">keiner</span> Sterne</td><td><span style="color:red;">keinen</span> Sterne<span style="color:red;">n</span></td><td><span style="color:darkviolet;">keine</span> Sterne</td></tr></tbody></table></div>';
    break;
  case 10:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Relativpronomen</span></h2><div class="grid-container55"><div><span style="color:red;">Kasus</span></div><div>M.</div><div>F.</div><div>N.</div><div>Pl.</div><div><span style="color:black;">Nominativ</span></div><div><span style="color:blue;">der</span></div><div><span style="color:red;">die</span></div><div><span style="color:green;">das</span></div><div><span style="color:orange;">die</span></div><div><span style="color:black;">Akkusativ</span></div><div><span style="color:blue;">den</span></div><div><span style="color:red;">die</span></div><div><span style="color:green;">das</span></div><div><span style="color:orange;">die</span></div><div><span style="color:black;">Dativ</span></div><div><span style="color:blue;">dem</span></div><div><span style="color:red;">der</span></div><div><span style="color:green;">dem</span></div><div><span style="color:orange;">denen</span></div><div><span style="color:black;">Genitiv</span></div><div><span style="color:blue;">dessen</span></div><div><span style="color:red;">deren</span></div><div><span style="color:green;">dessen</span></div><div><span style="color:orange;">deren</span></div></div>';
    break;
  case 11:
    day = '<h3>Unbestimmter Artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b>Kasus</b></td><td style="color:blue;"><b>M.</b></td><td style="color:red;"><b>F.</b></td><td style="color:green;"><b>N.</b></td><td><b>Pl.</b></td></tr><tr class="tr2"><td style="color:green;"><b>Nom.</b></td><td style="color:blue;">ein <span style="color:black;">Mann</span></td><td style="color:red;">eine <span style="color:black;">Frau</span></td><td style="color:green;">ein <span style="color:black;">Kind</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr><tr><td style="color:orange;"><b>Gen.</b></td><td style="color:blue;">eines <span style="color:black;">Mann</span><span style="color:orange;">es</span></td><td style="color:red;">einer <span style="color:black;">Frau</span></td><td style="color:green;">eines <span style="color:black;">Kind</span><span style="color:orange;">es</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr><tr class="tr2"><td style="color:red;"><b>Dat.</b></td><td style="color:blue;">einem <span style="color:black;">Mann</span></td><td style="color:red;">einer <span style="color:black;">Frau</span></td><td style="color:green;">einem <span style="color:black;">Kind</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr><tr><td style="color:darkviolet;"><b>Akk.</b></td><td style="color:blue;">einen <span style="color:black;">Mann</span></td><td style="color:red;">eine <span style="color:black;">Frau</span></td><td style="color:green;">ein <span style="color:black;">Kind</span></td><td style="color:black;">--- <span style="color:black;">Eltern</span></td></tr></tbody></table></div>';
    break;
  case 12:
    day = '<h3>Bestimmter Artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b>Kasus</b></td><td style="color:blue;"><b>M.</b></td><td style="color:red;"><b>F.</b></td><td style="color:green;"><b>N.</b></td><td><b>Pl.</b></td></tr><tr class="tr2"><td style="color:green;"><b>Nom.</b></td><td style="color:blue;">der <span style="color:black;">Mann</span></td><td style="color:red;">die <span style="color:black;">Frau</span></td><td style="color:green;">das <span style="color:black;">Kind</span></td><td style="color:black;">die <span style="color:black;">Eltern</span></td></tr><tr><td style="color:orange;"><b>Gen.</b></td><td style="color:blue;">des <span style="color:black;">Mann</span><span style="color:orange;">es</span></td><td style="color:red;">der <span style="color:black;">Frau</span></td><td style="color:green;">des <span style="color:black;">Kind</span><span style="color:orange;">es</span></td><td style="color:black;">der <span style="color:black;">Eltern</span></td></tr><tr class="tr2"><td style="color:red;"><b>Dat.</b></td><td style="color:blue;">dem <span style="color:black;">Mann</span></td><td style="color:red;">der <span style="color:black;">Frau</span></td><td style="color:green;">dem <span style="color:black;">Kind</span></td><td style="color:black;">den <span style="color:black;">Eltern</span></td></tr><tr><td style="color:darkviolet;"><b>Akk.</b></td><td style="color:blue;">den <span style="color:black;">Mann</span></td><td style="color:red;">die <span style="color:black;">Frau</span></td><td style="color:green;">das <span style="color:black;">Kind</span></td><td style="color:black;">die <span style="color:black;">Eltern</span></td></tr></tbody></table></div>';
    break;
  case 13:
    day = '<h3>Demostrativ artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td>Nominativ <span style="color:blue;"></span></td><td>Akkusativ<span style="color:blue;"></span></td></tr></thead><tbody class="body1"><tr class="tr2"><td><span style="color:blue;">der </span> da.</td><td><span style="color:blue;">den </span> hier.</td></tr><tr><td><span style="color:green;">das</span> da.</td><td><span style="color:green;">das </span> hier.</td></tr><tr class="tr2"><td><span style="color:red;">die </span> da.</td><td><span style="color:red;">die </span> hier.</td></tr></tbody></table></div>';
    break;
  case 14:
    day = '<h3>Artikel und Personalpronomen</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><tbody class="body1"><tr class="tr2"><td><span style="color:blue;">der</span> Computer</td><td>Er ist kaputt.</td></tr><tr><td><span style="color:green;">das</span> Tablet</td><td>Es ist weg.</td></tr><tr class="tr2"><td><span style="color:red;">die</span> Maus</td><td>Sie ist nicht weg.</td></tr></tbody></table></div>';
    break;
  case 15:
    day = '<h3>Adjektivdeklination-ohne Artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td></td><td><b><span style="color:green;">Nom.</span></b></td><td><b><span style="color:orange;">Genitiv</span></b></td><td><b><span style="color:red;">Dativ</span></b></td><td><b><span style="color:darkviolet;">Akk.</span></b></td></tr></thead><tbody class="body1"><tr><td><b>M.</b></td><td>Schön<span style="color:green;">er</span> Mann</td><td>Schön<span style="color:orange;">en</span> Mann<span style="color:orange;">es</span></td><td>Schön<span style="color:red;">em</span> Mann</td><td>Schön<span style="color:darkviolet;">en</span> Mann</td></tr><tr><td><b>N.</b></td><td>Schön<span style="color:green;">es</span> Haus</td><td>Schön<span style="color:orange;">en</span> Haus<span style="color:orange;">es</span></td><td>Schön<span style="color:red;">em</span> Haus</td><td>Schön<span style="color:darkviolet;">es</span> Haus</td></tr><tr><td><b>F.</b></td><td>Schön<span style="color:green;">e</span> Frau</td><td>Schön<span style="color:orange;">er</span> Frau<span style="color:orange;"></span></td><td>Schön<span style="color:red;">er</span> Frau</td><td>Schön<span style="color:darkviolet;">e</span> Frau</td></tr><tr><td><b>Pl.</b></td><td>Schön<span style="color:green;">e</span> Frauen</td><td>Schön<span style="color:orange;">er</span> Frauen<span style="color:orange;"></span></td><td>Schön<span style="color:red;">en</span> Frauen</td><td>Schön<span style="color:darkviolet;">e</span> Frauen</td></tr></tbody></table></div>';
    break;
  case 16:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Demostrativpronomen</span></h2><div class="grid-container55"><div><span style="color:red;">Kasus</span></div><div><span style="color:blue;">der</span></div><div><span style="color:green;">das</span></div><div><span style="color:red;">die</span></div><div>Pl.</div><div><span style="color:black;">Nominativ</span></div><div>dies<span style="color:blue;">er</span></div><div>dies<span style="color:green;">es</span></div><div>dies<span style="color:red;">e</span></div><div>dies<span>e</span></div><div><span style="color:black;">Akkusativ</span></div><div>dies<span style="color:blue;">en</span></div><div>dies<span style="color:green;">es</span></div><div>dies<span style="color:red;">e</span></div><div>dies<span>e</span></div><div><span style="color:black;">Dativ</span></div><div>dies<span style="color:blue;">em</span></div><div>dies<span style="color:green;">em</span></div><div>dies<span style="color:red;">er</span></div><div>dies<span>en</span></div><div><span style="color:black;">Genitiv</span></div><div>dies<span style="color:blue;">es</span></div><div>dies<span style="color:green;">es</span></div><div>dies<span style="color:red;">er</span></div><div>dies<span>er</span></div></div>';
    break;
  case 17:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Relativpronomen</span></h2><div class="grid-container55"><div><span style="color:red;">Kasus</span></div><div>M.</div><div>F.</div><div>N.</div><div>Pl.</div><div><span style="color:black;">Nominativ</span></div><div><span style="color:blue;">der</span></div><div><span style="color:red;">die</span></div><div><span style="color:green;">das</span></div><div><span style="color:orange;">die</span></div><div><span style="color:black;">Akkusativ</span></div><div><span style="color:blue;">den</span></div><div><span style="color:red;">die</span></div><div><span style="color:green;">das</span></div><div><span style="color:orange;">die</span></div><div><span style="color:black;">Dativ</span></div><div><span style="color:blue;">dem</span></div><div><span style="color:red;">der</span></div><div><span style="color:green;">dem</span></div><div><span style="color:orange;">denen</span></div><div><span style="color:black;">Genitiv</span></div><div><span style="color:blue;">dessen</span></div><div><span style="color:red;">deren</span></div><div><span style="color:green;">dessen</span></div><div><span style="color:orange;">deren</span></div></div>';
    break;
  case 18:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Reflexivpronomen</span></h2><div class="grid-container"><div><span style="color:darkviolet;">Akkusativ</span></div><div>mich</div><div>dich</div><div>sich</div><div>sich</div><div>sich</div><div>uns</div><div>euch</div><div>sich</div><div>sich</div><div><span style="color:red;">Dativ</span></div><div>mir</div><div>dir</div><div>sich</div><div>sich</div><div>sich</div><div>uns</div><div>euch</div><div>sich</div><div>sich</div></div><p>Die Reflexivponomen stehen nicht im Nominativ und im Genitiv kommen sie sehr selten vor. Das Reflexivpronomen stimmt mit dem subjekt des Satzes in Person und Numerus überein.</p></div>';
    break;
  case 19:
    day = '<div class="container mt-" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Pronomen</span></h2><div class="grid-container"><div><span style="color:green;">Nominativ</span></div><div>ich</div><div>du</div><div>er</div><div>sie</div><div>es</div><div>wir</div><div>ihr</div><div>sie</div><div>Sie</div><div><span style="color:darkviolet;">Akkusativ</span></div><div>mich</div><div>dich</div><div>ihn</div><div>sie</div><div>es</div><div>uns</div><div>euch</div><div>sie</div><div>Sie</div><div><span style="color:red;">Dativ</span></div><div>mir</div><div>dir</div><div>ihm</div><div>ihr</div><div>ihm</div><div>uns</div><div>euch</div><div>ihnen</div><div>Ihnen</div><div><span style="color:orange;">Possessiv</span></div><div>mein</div><div>dein</div><div>sein</div><div>ihr</div><div>sein</div><div>unser</div><div>euer</div><div>ihr</div><div>Ihr</div></div></div>';
    break;
  case 20:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;">Possessivpronomen Genitiv</h2><table><thead><tr class="tr1"><th></th><th><span style="color:blue;">der</span></th><th><span style="color:green;">das</span></th><th><span style="color:red;">die</span></th><th>Plural</th></tr></thead><tbody><tr><td><b>ich</b></td><td>meines</td><td>meines</td><td>meiner</td><td>meiner</td></tr><tr class="tr2"><td><b>du</b></td><td>deines</td><td>deines</td><td>deiner</td><td>deiner</td></tr><tr><td><b>er</b></td><td>seines</td><td>seines</td><td>seiner</td><td>seiner</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihres</td><td>ihres</td><td>ihrer</td><td>ihrer</td></tr><tr><td><b>es</b></td><td>seines</td><td>seines</td><td>seiner</td><td>seiner</td></tr><tr class="tr2"><td><b>wir</b></td><td>unseres</td><td>unseres</td><td>unserer</td><td>unserer</td></tr><tr><td><b>ihr</b></td><td>eueres</td><td>eueres</td><td>euerer</td><td>euerer</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihres</td><td>ihres</td><td>ihrer</td><td>ihrer</td></tr><tr><td><b>Sie</b></td><td>Ihres</td><td>Ihres</td><td>Ihrer</td><td>Ihrer</td></tr></tbody></table></div>';
    break;
  case 21:
    day = '<h3>Bestimmter Artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b>Kasus</b></td><td style="color:blue;"><b>M.</b></td><td style="color:red;"><b>F.</b></td><td style="color:green;"><b>N.</b></td><td><b>Pl.</b></td></tr><tr class="tr2"><td style="color:green;"><b>Nom.</b></td><td style="color:blue;">der <span style="color:black;">Mann</span></td><td style="color:red;">die <span style="color:black;">Frau</span></td><td style="color:green;">das <span style="color:black;">Kind</span></td><td style="color:black;">die <span style="color:black;">Eltern</span></td></tr><tr><td style="color:orange;"><b>Gen.</b></td><td style="color:blue;">des <span style="color:black;">Mann</span><span style="color:orange;">es</span></td><td style="color:red;">der <span style="color:black;">Frau</span></td><td style="color:green;">des <span style="color:black;">Kind</span><span style="color:orange;">es</span></td><td style="color:black;">der <span style="color:black;">Eltern</span></td></tr><tr class="tr2"><td style="color:red;"><b>Dat.</b></td><td style="color:blue;">dem <span style="color:black;">Mann</span></td><td style="color:red;">der <span style="color:black;">Frau</span></td><td style="color:green;">dem <span style="color:black;">Kind</span></td><td style="color:black;">den <span style="color:black;">Eltern</span></td></tr><tr><td style="color:darkviolet;"><b>Akk.</b></td><td style="color:blue;">den <span style="color:black;">Mann</span></td><td style="color:red;">die <span style="color:black;">Frau</span></td><td style="color:green;">das <span style="color:black;">Kind</span></td><td style="color:black;">die <span style="color:black;">Eltern</span></td></tr></tbody></table></div>';
    break;
  case 22:
    day = '<div><h1><span style="color:red;">DATIV</span> - Zeitangaben</h1></button> Artikel <span style="color:blue;">der</span> / <span style="color:green;">das</span> im Dativ: =  <span style="color:red;">dem</span><br>Datum/Wochentag:  <span style="color:red;">a</span>n  +  de<span style="color:red;">m</span>  =  <span style="color:red;">am</span>:  <span style="color:red;">am</span> erst<span style="color:red;">en</span>, zweit<span style="color:red;">en</span>, dritt<span style="color:red;">en</span>, viert<span style="color:red;">en</span> .....<br>Monat/Jahreszeit: <span style="color:red;">i</span>n +  de<span style="color:red;">m</span>  =  <span style="color:red;">im</span>:  <span style="color:red;">im</span> Januar, Februar, <span style="color:red;">im</span> Sommer, Herbst .....<br><br><span style="color:red;">FOKUS</span>         Verben mit Akkusativ und Dativ<br>Dativ   -   Person <br> Akkusativ   -   Sache </div>';
    break;
  case 23:
    day = '<div class="container mt-3" style="overflow: auto;"><h2 style="text-align:center; color:black;" >Possessivpronomen Nominativ</h2><table><thead><tr class="tr1"><th></th><th><span style="color:blue;">der</span></th><th><span style="color:green;">das</span></th><th><span style="color:red;">die</span></th><th>Plural</th></tr></thead><tbody><tr><td><b>ich</b></td><td>mein</td><td>mein</td><td>meine</td><td>meine</td></tr><tr class="tr2"><td><b>du</b></td><td>dein</td><td>dein</td><td>deine</td><td>deine</td></tr><tr><td><b>er</b></td><td>sein</td><td>sein</td><td>seine</td><td>seine</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihr</td><td>ihr</td><td>ihre</td><td>ihre</td></tr><tr><td><b>es</b></td><td>sein</td><td>sein</td><td>seine</td><td>seine</td></tr><tr class="tr2"><td><b>wir</b></td><td>unser</td><td>unser</td><td>unsere</td><td>unsere</td></tr><tr><td><b>ihr</b></td><td>euer</td><td>euer</td><td>euere</td><td>euere</td></tr><tr class="tr2"><td><b>sie</b></td><td>ihr</td><td>ihr</td><td>ihre</td><td>ihre</td></tr><tr><td><b>Sie</b></td><td>Ihr</td><td>Ihr</td><td>Ihre</td><td>Ihre</td></tr></tbody></table></div>';
    break;
  case 24:
    day = '<h3>Demostrativ artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td>Nominativ <span style="color:blue;"></span></td><td>Akkusativ<span style="color:blue;"></span></td></tr></thead><tbody class="body1"><tr class="tr2"><td><span style="color:blue;">der </span> da.</td><td><span style="color:blue;">den </span> hier.</td></tr><tr><td><span style="color:green;">das</span> da.</td><td><span style="color:green;">das </span> hier.</td></tr><tr class="tr2"><td><span style="color:red;">die </span> da.</td><td><span style="color:red;">die </span> hier.</td></tr></tbody></table></div>';
    break;
  case 25:
    day = '<div><h1>Kasus, Numerus, Genus</h1><p><h2><span style="color:red;">Kasus</span></h2><span style="font-size:20px;">&#8594;</span>Fall<br>1.) Nominativ<br>2.) Genitiv<br>3.) Dativ<br>4.) Akkusativ</p><br><p><h2><span style="color:red;">Numerus</span></h2><span style="font-size:20px;">&#8594;</span>Einzahl / Mehrzahl<br>1.) Singular<br>2.) Plural</p><br><p><h2><span style="color:red;">Genus</span></h2><span style="font-size:20px;">&#8594;</span>Geschlecht<br>1.) Maskulin <span style="color:blue;">der</span><br>2.) Feminin <span style="color:red;">die</span><br>3.) Neutral <span style="color:green;">das</span></p></div>';
    break;
  case 26:
    day = '<h3>Frage artikel</h3><div class="container mt-3" style="overflow: auto;"><h3>Frageartikel  Welcher?  Welches?  Welche?</h3><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b><span style="color:green;">Nominativ</span></b></td><td><b><span style="color:darkviolet;">Akkusativ</span></td></tr></thead><tbody class="body1"><tr class="tr2"><td>Welch<span style="color:blue;">er </span> Apfel?</td><td>Welch<span style="color:blue;">en </span> Apfel?</td></tr><tr><td class="w3-text-">Welch<span style="color:green;">es</span> Herz?</td><td>Welch<span style="color:green;">es </span> Herz?</td></tr><tr class="tr2"><td>Welch<span style="color:red;">e </span> Banane?</td><td>Welch<span style="color:red;">e </span> Banane?</td></tr></tbody></table></div>';
    break;
  case 27:
    day = '<h3>Negativartikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b></b></td><td><b><span style="color:green;">Nom.</span></b></td><td><b><span style="color:orange;">Genitiv</span></b></td><td><b><span style="color:red;">Dativ</span></b></td><td><b><span style="color:darkviolet;">Akk.</span></b></td></tr></thead><tbody class="body1"><tr class="tr2"><td><b><span style="color:blue;">der</span></b></td><td><span style="color:green;">kein</span> Mann</td><td><span style="color:orange;">keines</span> Mann<span style="color:orange;">es</span></td><td><span style="color:red;">keinem</span> Mann</td><td><span style="color:darkviolet;">keinen</span> Mann</td></tr><tr><td><b><span style="color:red;">die</span></b></td><td><span style="color:green;">keine</span> Frau</td><td><span style="color:orange;">keiner</span> Frau</td><td><span style="color:red;">keiner</span> Frau</td><td><span style="color:darkviolet;">keine</span> Frau</td></tr><tr class="tr2"><td><b><span style="color:green;">das</span></b></td><td><span style="color:green;">kein</span> Kind</td><td><span style="color:orange;">keines</span> Kind<span style="color:orange;">es</span></td><td><span style="color:red;">keinem</span> Kind</td><td><span style="color:darkviolet;">kein</span> Kind</td></tr><tr><td><b>Pl.</b></td><td><span style="color:green;">keine</span> Sterne</td><td><span style="color:orange;">keiner</span> Sterne</td><td><span style="color:red;">keinen</span> Sterne<span style="color:red;">n</span></td><td><span style="color:darkviolet;">keine</span> Sterne</td></tr></tbody></table></div>';
    break;
  case 28:
    day = '<h3>Demostrativ artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td>Nominativ <span style="color:blue;"></span></td><td>Akkusativ<span style="color:blue;"></span></td></tr></thead><tbody class="body1"><tr class="tr2"><td><span style="color:blue;">der </span> da.</td><td><span style="color:blue;">den </span> hier.</td></tr><tr><td><span style="color:green;">das</span> da.</td><td><span style="color:green;">das </span> hier.</td></tr><tr class="tr2"><td><span style="color:red;">die </span> da.</td><td><span style="color:red;">die </span> hier.</td></tr></tbody></table></div>';
    break;
  case 29:
    day = '<h3>Artikel und Personalpronomen</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><tbody class="body1"><tr class="tr2"><td><span style="color:blue;">der</span> Computer</td><td>Er ist kaputt.</td></tr><tr><td><span style="color:green;">das</span> Tablet</td><td>Es ist weg.</td></tr><tr class="tr2"><td><span style="color:red;">die</span> Maus</td><td>Sie ist nicht weg.</td></tr></tbody></table></div>';
    break;
  case 30:
    day = '<h3>Bestimmter Artikel</h3><div class="container mt-3" style="overflow: auto;"><table class="table-bordered"><thead class="body1"><tr class="tr1"><td><b>Kasus</b></td><td style="color:blue;"><b>M.</b></td><td style="color:red;"><b>F.</b></td><td style="color:green;"><b>N.</b></td><td><b>Pl.</b></td></tr><tr class="tr2"><td style="color:green;"><b>Nom.</b></td><td style="color:blue;">der <span style="color:black;">Mann</span></td><td style="color:red;">die <span style="color:black;">Frau</span></td><td style="color:green;">das <span style="color:black;">Kind</span></td><td style="color:black;">die <span style="color:black;">Eltern</span></td></tr><tr><td style="color:orange;"><b>Gen.</b></td><td style="color:blue;">des <span style="color:black;">Mann</span><span style="color:orange;">es</span></td><td style="color:red;">der <span style="color:black;">Frau</span></td><td style="color:green;">des <span style="color:black;">Kind</span><span style="color:orange;">es</span></td><td style="color:black;">der <span style="color:black;">Eltern</span></td></tr><tr class="tr2"><td style="color:red;"><b>Dat.</b></td><td style="color:blue;">dem <span style="color:black;">Mann</span></td><td style="color:red;">der <span style="color:black;">Frau</span></td><td style="color:green;">dem <span style="color:black;">Kind</span></td><td style="color:black;">den <span style="color:black;">Eltern</span></td></tr><tr><td style="color:darkviolet;"><b>Akk.</b></td><td style="color:blue;">den <span style="color:black;">Mann</span></td><td style="color:red;">die <span style="color:black;">Frau</span></td><td style="color:green;">das <span style="color:black;">Kind</span></td><td style="color:black;">die <span style="color:black;">Eltern</span></td></tr></tbody></table></div>';
    break;
  case  31:
    day = '<div class="container mt-" style="overflow: auto;"><h2 style="text-align:center; color:black;"><span style="color:red;">Pronomen</span></h2><div class="grid-container"><div><span style="color:green;">Nominativ</span></div><div>ich</div><div>du</div><div>er</div><div>sie</div><div>es</div><div>wir</div><div>ihr</div><div>sie</div><div>Sie</div><div><span style="color:darkviolet;">Akkusativ</span></div><div>mich</div><div>dich</div><div>ihn</div><div>sie</div><div>es</div><div>uns</div><div>euch</div><div>sie</div><div>Sie</div><div><span style="color:red;">Dativ</span></div><div>mir</div><div>dir</div><div>ihm</div><div>ihr</div><div>ihm</div><div>uns</div><div>euch</div><div>ihnen</div><div>Ihnen</div><div><span style="color:orange;">Possessiv</span></div><div>mein</div><div>dein</div><div>sein</div><div>ihr</div><div>sein</div><div>unser</div><div>euer</div><div>ihr</div><div>Ihr</div></div></div>';
    break;
  default:
     day = "unknown";
}
document.getElementById("demoode").innerHTML = "<b></b> <br>" + day;